import { RentalCategory } from "./rentalTypes";

export const rentalCategories: RentalCategory[] = [
  {
    id: "bars",
    name: "Bars",
    subcategories: [
      {
        id: "bar",
        name: "Bar",
        description: "Handcrafted bars for your beverage service needs",
        items: [
          {
            id: "the-magnolia",
            name: "The MAGNOLIA",
            subtitle: "6' Customizable Bar",
            description: "Sleek and timeless, this handmade white wood bar complements any event theme and is easily customizable. Panel Sizing __________ Bar Fits 2 comfortably.",
            image: "/images/rentals/placeholder.jpg",
            dimensions: "H 44 L 72.75 W24.25 Fits 2 bartenders comfortably",
            quantity: "1",
          },
          {
            id: "the-fiore",
            name: "The Fiore",
            subtitle: "6' Italian Tiled White Bar",
            description: "A modern white bar accented with Italian tiles for a touch of European charm  Bar Fits 2 comfortably.",
            image: "/images/rentals/TheFiore6'ItalianTiledWhiteBar.jpg",
            images: ["/images/rentals/TheFiore6'ItalianTiledWhiteBar2.jpg"],
            dimensions: "H 44 L 72.75 W24.25 Fits 2 bartenders comfortably",
            quantity: "1",
          },
          {
            id: "the-olive",
            name: "The Olive",
            subtitle: "6' Green Tiled Bar",
            description: "Handmade Wood bar featuring deep green tiles and concrete bartop for a touch of natural ambiance. Bar Fits 2 comfortably.",
            image: "/images/rentals/TheOlive6'GreenTiledBar.jpg",
            dimensions: "H 44 L 72.75 W24.25 Fits 2 bartenders comfortably",
            quantity: "1",
          },
          {
            id: "the-gardenia",
            name: "The Gardenia",
            subtitle: "8' White Drink Display + 8' Fern Wall",
            description: "2 Arched Bookcases perfect for displaying glassware, florals, or bottles paired with Fern Wall covering remaining sides.",
            image: "/images/rentals/TheGardenia8'WhiteDrinkDisplay+8'FernWall.jpg",
            images: ["/images/rentals/TheGardenia8'WhiteDrinkDisplay+8'FernWall1.jpg", "/images/rentals/TheGardenia8'WhiteDrinkDisplay+8'FernWall3.jpg"],
            dimensions: "8x8 2(4x8)",
            quantity: "1",
          },
          {
            id: "the-olive-side-table",
            name: "The Olive: Side Table",
            subtitle: "4' Green Tiled Bar",
            description: "Handmade Wood bar featuring deep green tiles and concrete bartop for a touch of natural ambiance.",
            image: "/images/rentals/TheOlive:SideTable4'GreenTiledBar .jpg",
            dimensions: "H 45 L 50.5/ 49",
            quantity: "2",
          },
        ],
      },
      {
        id: "drink-displays",
        name: "Drink Displays",
        description: "Elegant displays for showcasing beverages",
        items: [
          {
            id: "the-gardenia",
            name: "The Gardenia",
            subtitle: "8' White Drink Display + 8' Fern Wall",
            description: "2 Arched Bookcases perfect for displaying glassware, florals, or bottles paired with Fern Wall covering remaining sides.",
            image: "/images/rentals/TheGardenia8'WhiteDrinkDisplay+8'FernWall.jpg",
            images: ["/images/rentals/TheGardenia8'WhiteDrinkDisplay+8'FernWall1.jpg", "/images/rentals/TheGardenia8'WhiteDrinkDisplay+8'FernWall3.jpg"],
            dimensions: "8x8 2(4x8)",
            quantity: "1",
          },
        ],
      },
    ],
  },
  {
    id: "decor",
    name: "Decor",
    subcategories: [
      {
        id: "large-decor",
        name: "Large Decor",
        description: "Statement pieces that transform your space",
        items: [
          {
            id: "the-camellia",
            name: "The Camellia",
            subtitle: "8' White Arch",
            description: "Make a statement with our stunning 8ft White Arch — a timeless piece that elevates any event design. Crafted with a smooth, clean finish and graceful curves, this versatile structure serves as the perfect backdrop for ceremonies or photo moments",
            image: "/images/rentals/TheCamellia8'WhiteArch.jpg",
            images: ["/images/rentals/TheCamellia8'WhiteArch2.jpg"],
            dimensions: "4x8",
            quantity: "2",
          },
          {
            id: "the-papavero",
            name: "The Papavero",
            subtitle: "Large Italian Fountain",
            description: "Handcrafted Italian-inspired fountain. Designed with intricate blue and yellow mosaic tiles framed by textured white stone",
            image: "/images/rentals/ThePapaveroLargeItalianFountain.jpg",
            images: ["/images/rentals/ThePapaveroLargeItalianFountain2.jpg", "/images/rentals/ThePapaveroLargeItalianFountain3.jpg"],
            dimensions: "H 60 W 35",
            quantity: "1",
          },
          {
            id: "the-juniper",
            name: "The Juniper",
            subtitle: "12' Fern Wall",
            description: "Lush mix of artificial greenery perfect for photo backdrops or accent walls.",
            image: "/images/rentals/TheJuniper12'FernWall .png",
            dimensions: "8x8",
            quantity: "1",
          },
        ],
      },
      {
        id: "small-decor",
        name: "Small Decor",
        description: "Charming accents that add character",
        items: [
          {
            id: "the-fern",
            name: "The FERN",
            subtitle: "Brass Bird Cage",
            description: "Whimsical gold bird cage with leaf detail, ideal for candles or florals.",
            image: "/images/rentals/TheFERNBrassBirdCage.jpg",
            dimensions: "13 | 13 | 16.5",
            quantity: "3",
          },
        ],
      },
      {
        id: "candle-holders-votives",
        name: "Candle Holders + Votives",
        description: "Elegant lighting solutions for ambient atmosphere",
        items: [
          {
            id: "the-lotus",
            name: "The Lotus",
            subtitle: "Tall Glass Candle Holder",
            description: "Clear glass Taper Candle Holder. Statement pieces for romantic ambient lighting. **Candle sticks must be purchased separately are not included in rental.",
            image: "/images/rentals/TheLotusTallGlassCandlerHolder.jpg",
            images: ["/images/rentals/TheLotusTallGlassCandlerHolder2.jpg", "/images/rentals/TheLotusTallGlassCandlerHolder3.jpg"],
            dimensions: "H 4\"",
            quantity: "24",
          },
          {
            id: "the-jasmine",
            name: "The Jasmine",
            subtitle: "Short Glass Candle Holder",
            description: "Ribbed glass Taper Candle Holder **Candle sticks must be purchased separately are not included in rental.",
            image: "/images/rentals/TheJasmineShortGlassCandleHolder.jpg",
            images: ["/images/rentals/TheJasmineShortGlassCandleHolder1.jpg"],
            dimensions: "H 2.76 D 1.77",
            quantity: "60",
          },
          {
            id: "the-lariat-collection",
            name: "The Lariat Collection",
            subtitle: "Clear Crystal Candle Holder",
            description: "Authentic vintage glass pieces with intricate detail. Candle Holder Collection includes 2 Tall Candle Holders and 2 Short Candle Holders",
            image: "/images/rentals/TheLariatCollectionClearCrystalCandleHolder.jpg",
            images: ["/images/rentals/TheLariatCollectionClearCrystalCandleHolder2.jpg"],
            dimensions: "Tall: H 7 Short: H 5",
            quantity: "4",
          },
          {
            id: "the-amaryllis",
            name: "The Amaryllis",
            subtitle: "Blue Glass Candle Holder",
            description: "Small Blue Round Glass Bowl Tea candle holder",
            image: "/images/rentals/placeholder.jpg",
            dimensions: "H 3",
            quantity: "3",
          },
        ],
      },
      {
        id: "decanter-vases",
        name: "Decanter + Vases",
        description: "Timeless vessels for florals and displays",
        items: [
          {
            id: "the-freesia-collection",
            name: "The Freesia Collection",
            subtitle: "Vintage Glass Bud Vase",
            description: "Small Vintage Glass bottles/ bud vases Timeless accents that bring character and charm to any display.",
            image: "/images/rentals/TheFreesiaCollectionVintageClearGlassBottles.jpg",
            images: ["/images/rentals/TheFreesiaCollectionVintageClearGlassBottles1.jpg", "/images/rentals/TheFreesiaCollectionVintageClearGlassBottles3.jpg"],
            dimensions: "varies",
            quantity: "64",
          },
          {
            id: "the-delphinium",
            name: "The Delphinium",
            subtitle: "Blue Glass Vase",
            description: "The tall silhouette and glassy, cloud-blue finish create a serene, romantic statement, perfect for showcasing single stems, airy arrangements, or standing beautifully on its own. Its waved rim adds movement and artistry, making it a subtle yet striking accent for modern or garden-inspired decor.",
            image: "/images/rentals/TheDelphiniumBlueGlassVase.jpg",
            dimensions: "H 9 | 12.5",
            quantity: "3",
          },
        ],
      },
      {
        id: "trays",
        name: "Trays",
        description: "Sophisticated serving and display pieces",
        items: [
          {
            id: "the-aurelia",
            name: "The Aurelia",
            subtitle: "Gold Oval Mirror Tray",
            description: "Antique Gold polished mirror tray with floral detail around sides and handles. Ideal for styling",
            image: "/images/rentals/TheAureliaGoldOvalMirrorTray.jpg",
            dimensions: "L 20 D11.5",
            quantity: "1",
          },
        ],
      },
    ],
  },
  {
    id: "lounge-furniture",
    name: "Lounge Furniture",
    subcategories: [
      {
        id: "lounge-tables",
        name: "Lounge Tables",
        description: "Statement tables for gathering spaces",
        items: [
          {
            id: "the-bluebell",
            name: "The Bluebell",
            subtitle: "Royal Blue Velvet Sofa",
            description: "Plush, luxurious velvet seating with a bold color statement. Comfortably fits 2/3",
            image: "/images/rentals/TheBluebellRoyalBlueVelvetSofa.jpg",
            images: ["/images/rentals/TheBluebellRoyalBlueVelvetSofa2.jpg", "/images/rentals/TheBluebellRoyalBlueVelvetSofa3.jpg", "/images/rentals/TheBlueSofaLounge.jpg", "/images/rentals/TheBlueSofaLounge2.jpg", "/images/rentals/TheBlueSofaLounge3.jpg"],
            dimensions: "L 78 W 32 H 31",
            quantity: "1",
          },
        ],
      },
      {
        id: "end-tables",
        name: "End Tables",
        description: "Refined accent tables",
        items: [
          {
            id: "the-calendula-oval",
            name: "The Calendula: Oval",
            subtitle: "Oval Marbled Coffee Table",
            description: "",
            image: "/images/rentals/TheCalendula:OvalOvalMarbledCoffeeTable.jpg",
            images: ["/images/rentals/TheCalendula.jpg", "/images/rentals/TheCalendula1.jpg"],
            dimensions: "H 18.5 L 47",
            quantity: "1",
          },
          {
            id: "the-calendula-round",
            name: "The Calendula: round",
            subtitle: "Round Marbled End Table",
            description: "Elegant side table combining marble textures and gold tones.",
            image: "/images/rentals/TheCalendula:roundRoundMarbledEndTable .jpg",
            dimensions: "H24 L 23.75",
            quantity: "1",
          },
          {
            id: "the-dahlia",
            name: "The Dahlia",
            subtitle: "Brass Mirrored End Table",
            description: "Beautiful bold blend between goldtone metal and mirrored glass adds a level of depth to any event",
            image: "/images/rentals/TheDahliaBrassMirroredEndTable .jpg",
            dimensions: "H 32.5 L 27",
            quantity: "Available",
          },
        ],
      },
    ],
  },
  {
    id: "lighting",
    name: "Lighting",
    subcategories: [
      {
        id: "statement-lighting",
        name: "Statement Lighting",
        description: "Dramatic lighting pieces that captivate",
        items: [
          {
            id: "the-indigo-bloom",
            name: "The Indigo Bloom",
            subtitle: "Handmade Tassel Chandelier",
            description: "Handcrafted with artistry and intention, the Royal Blue Tassel Chandelier is a stunning statement piece that brings texture, movement, and depth to any space. Designed with three cascading tiers of soft tassels, it flows effortlessly around a central pendant light, creating a dreamy play of light and shadow.",
            image: "/images/rentals/TheIndigoBloomHandmadeTasselChandelier .jpg",
            images: ["/images/rentals/TheIndigoBloomHandmadeTasselChandelier2 .jpg", "/images/rentals/TheIndigoBloomHandmadeTasselChandelier3.jpg", "/images/rentals/TheIndigoBloomHandmadeTasselChandelier4.jpg"],
            dimensions: "34 before bulb",
            quantity: "2",
          },
        ],
      },
      {
        id: "table-top-lighting",
        name: "Table Top Lighting",
        description: "Intimate lighting for tablescapes",
        items: [
          {
            id: "the-poppy",
            name: "The Poppy",
            subtitle: "Handmade Floral Taper Candles",
            description: "Elegant white pillar candles adorned with delicate handmade paper flowers in soft, romantic hues. Each candle features carefully placed blossoms in customizable colors with pearl-like centers that catch the light beautifully. The flowers are artfully arranged along the length of each candle, creating a charming garden-inspired aesthetic.",
            image: "/images/rentals/ThePoppyHandmadeFloralTaperCandles.jpg",
            images: ["/images/rentals/ThePoppyHandmadeFloralTaperCandles2.jpg", "/images/rentals/ThePoppyHandmadeFloralTaperCandles3.jpg", "/images/rentals/ThePoppyHandmadeFloralTaperCandles4.jpg"],
            dimensions: "Customizable Candle/ Flower Color $20",
            quantity: "40",
          },
        ],
      },
    ],
  },
  {
    id: "table-top",
    name: "Table Top",
    subcategories: [
      {
        id: "dinnerware",
        name: "Dinnerware",
        description: "Elegant place settings",
        items: [
          {
            id: "the-marigold",
            name: "the Marigold",
            subtitle: "Gold Beaded Charger",
            description: "Clear Gold Beaded Charger Plates Elegant base pieces to elevate your table design.",
            image: "/images/rentals/theMarigoldGoldBeadedCharger.jpg",
            images: ["/images/rentals/theMarigoldGoldBeadedCharger1.jpg", "/images/rentals/theMarigoldGoldBeadedCharger2.jpg"],
            dimensions: "13 in round/ Plastic",
            quantity: "50",
          },
          {
            id: "the-petal",
            name: "The Petal",
            subtitle: "Pink Floral Plate",
            description: "Soft, feminine square glass pink plates with intricate floral detailing painted on.",
            image: "/images/rentals/ThePetalPinkFloralPlate.jpg",
            images: ["/images/rentals/ThePetalPinkFloralPlate3.jpg", "/images/rentals/ThePetalPinkFloralPlate4.jpg"],
            dimensions: "L 8 W 8",
            quantity: "8",
          },
        ],
      },
      {
        id: "accessories",
        name: "Accessories",
        description: "Refined details for your tablescape",
        items: [
          {
            id: "the-willow",
            name: "The Willow",
            subtitle: "Sage Green Linen Napkin",
            description: "Sage Green Polyestrer Linen Napkins",
            image: "/images/rentals/TheWillowSageGreenLinenNapkin.jpg",
            images: ["/images/rentals/TheWillowSageGreenLinenNapkin1.jpg", "/images/rentals/TheWillowSageGreenLinenNapkin2.jpg"],
            dimensions: "17\"x 17\"",
            quantity: "50",
          },
          {
            id: "the-rose",
            name: "The ROSE",
            subtitle: "Gold Rose and Pearl Napkin Ring",
            description: "Crafted from polished gold metal, this delicate piece features a white rose and pearl detail on either end, creating a soft, romantic charm that complements any tablescape.",
            image: "/images/rentals/TheROSEGoldRoseandPearlNapkinRing.jpg",
            images: ["/images/rentals/TheROSEGoldRoseandPearlNapkinRing2.jpg"],
            dimensions: "",
            quantity: "49",
          },
          {
            id: "the-viola",
            name: "The Viola",
            subtitle: "Blue Mediterranean Plate",
            description: "artisan-crafted pieces inspired by the charm of seaside dining. Each plate is handmade with subtle variations in color and texture, giving every piece its own character. Though designed as plates, their smaller size makes them perfect for use as decorative coasters or layering accents beneath chargers or glassware, adding a sophisticated pop of blue to your setting.",
            image: "/images/rentals/TheViolaBlueMediterraneanPlate.jpg",
            images: ["/images/rentals/TheViola BlueMediterraneanPlate.jpg", "/images/rentals/TheViolaBlueMediterraneanPlate-Type1.jpg", "/images/rentals/TheViolaBlueMediterraneanPlate-Type2.jpg", "/images/rentals/TheViolaBlueMediterraneanPlate-Type3.jpg", "/images/rentals/TheViolaBlueMediterraneanPlate1.jpg", "/images/rentals/TheViolaBlueMediterraneanPlate2.jpg"],
            dimensions: "L 8 D 8",
            quantity: "11",
          },
          {
            id: "the-lariat-collection",
            name: "The Lariat Collection",
            subtitle: "Clear Crystal Assortment",
            description: "Authentic vintage glass pieces with intricate detail. The Lariat Collection includes: 1 Vase 1 Bowl  2 Tall Candle Holders and 2 Short Candle Holders",
            image: "/images/rentals/TheLariatCollectionClearCrystalAssortment.jpg",
            images: ["/images/rentals/TheLariatCollectionClearCrystalAssortment2.jpg", "/images/rentals/TheLariatCollectionClearCrystalAssortment3.jpg"],
            dimensions: "Bowl: L 12 W 12 Vase: H 7.25 Tall: H 7 Short: H 5",
            quantity: "6",
          },
          {
            id: "the-mimosa-collection",
            name: "The Mimosa Collection",
            subtitle: "Colorful Glass Bottles",
            description: "Assorted Eclectic and vibrant colored glass bottles; perfect for adding playful texture.",
            image: "/images/rentals/TheMimosaCollectionColorfulGlassBottles.jpg",
            images: ["/images/rentals/TheMimosaCollectionColorfulGlassBottles1.jpg"],
            dimensions: "Varies",
            quantity: "Available",
          },
          {
            id: "the-freesia-collection",
            name: "The Freesia Collection",
            subtitle: "Vintage Clear Glass Bottles",
            description: "Small Vintage Glass bottles/ bud vases Timeless accents that bring character and charm to any display.",
            image: "/images/rentals/TheFreesiaCollectionVintageClearGlassBottles.jpg",
            images: ["/images/rentals/TheFreesiaCollectionVintageClearGlassBottles1.jpg", "/images/rentals/TheFreesiaCollectionVintageClearGlassBottles3.jpg"],
            dimensions: "Varies",
            quantity: "64",
          },
          {
            id: "the-frostflower",
            name: "The Frostflower",
            subtitle: "Tall Drink Cooler",
            description: "Portable standing cooler, easily customizable ideal for outdoor bar setups.",
            image: "/images/rentals/TheFrostflowerTallDrinkCooler.jpg",
            images: ["/images/rentals/TheFrostflowerTallDrinkCooler1.jpg"],
            dimensions: "72 Quart",
            quantity: "2",
          },
        ],
      },
      {
        id: "linens",
        name: "Linens",
        description: "Premium table linens",
        items: [
          {
            id: "the-snowdrop",
            name: "The Snowdrop",
            subtitle: "Solid White Linen | 70x 120 Rectangle",
            description: "Crisp, clean, and versatile to complement any tablescape.",
            image: "/images/rentals/TheSnowdropSolidWhiteLinen|70x120Rectangle.jpg",
            images: ["/images/rentals/TheSnowdropSolidWhiteLinen|70x120Rectangle .jpg"],
            dimensions: "6ft & 8ft tables",
            quantity: "9",
          },
        ],
      },
    ],
  },
];